# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: DAWN Research Group | Dr. Yunzhe Liu
first_name: Yunzhe
middle_name: 
last_name: Liu
contact_note: >
  email: yzliu@soci.ecnu.edu.cn
description: >
  Official website of the DAWN Research Group, led by Dr. Yunzhe Liu at East China Normal University. 华东师范大学 DAWN 课题组官方网站。
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: "刘贇喆, 华东师范大学, ECNU, DAWN Research Group, GeoAI" 
lang: en 

# 这里的逻辑是：如果是文件名，主题会自动去 assets/img/ 找
icon: logo.png

url: https://dawn-ecnu.github.io
baseurl: "" 
last_updated: true 
back_to_top: true 

# -----------------------------------------------------------------------------
# Collections (确保 Data 页面能被识别)
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  teachings:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings & Plugins
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jemoji

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_darkmode: true 
enable_progressbar: true 
enable_masonry: true 
enable_math: true